# Generated by Django 4.1.7 on 2023-03-02 11:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('midas_case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('result', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
